version: '3'
services:
  mysql:
    # Dockerfile이 있는 위치
    build: ./mysql
    # 내부에서 개방할 포트 : 외부에서 접근할 포트
    ports:
      - "3306:3306"
  python:
    build: ./python
    # 연결할 외부 디렉토리 : 컨테이너 내 디렉토리
    volumes:
      - ./python:/usr/src/app
    ports:
      - "5000:5000"
    # 환경변수 설정
    environment: 
      - DBHOST=mysql
  node:
    build: ./node
    volumes:
      - ./node:/home/node/app
    ports:
      - "8080:8080"
  go:
    build: ./go
    volumes:
      - ./go:/go/src/app
    ports:
      - "4000:4000"
    environment: 
      - DBHOST=mysql